Update pipeline Test af-component-agent

diff --git a/.harness/pipelines/test-af-component-agent.yaml b/.harness/pipelines/test-af-component-agent.yaml
--- a/.harness/pipelines/test-af-component-agent.yaml
+++ b/.harness/pipelines/test-af-component-agent.yaml
@@ -59,12 +59,12 @@ pipeline:
                           echo "DATAROBOT_ENDPOINT=https://test.com/api/v2" >> .env
 
                           # Run the CLI command with a sample user prompt
+                          echo "Initial execution"
                           uvx --from go-task-bin task agent:cli -- \
                             execute \
                             --show_output \
                             --user_prompt '{"topic": "Artificial Intelligence"}' \
                             > ./agent/output.log 2>&1
-
                           cat ./agent/output.log
 
                           # Check if the log file was created
@@ -78,58 +78,58 @@ pipeline:
                             exit 1
                           fi
 
-                          # echo "-------------------------------"
-                          # echo "Printing log file for debugging:"
-                          # cat ./agent/output.log
-                          # echo "-------------------------------"
+                          echo "-------------------------------"
+                          echo "Printing log file for debugging:"
+                          cat ./agent/output.log
+                          echo "-------------------------------"
 
-                          # # Check the logger showed the first command
-                          # if cat ./agent/output.log | grep -q 'Running CLI execute'; then
-                          #   echo "Test passed: cli.py returned log for starting cli"
-                          # else
-                          #   echo "Test failed: cli.py did not return log for starting cli"
-                          #   exit 1
-                          # fi
+                          # Check the logger showed the first command
+                          if cat ./agent/output.log | grep -q 'Running CLI execute'; then
+                            echo "Test passed: cli.py returned log for starting cli"
+                          else
+                            echo "Test failed: cli.py did not return log for starting cli"
+                            exit 1
+                          fi
 
-                          # # Check the logger showed the startup commands
-                          # if cat ./agent/output.log | grep -q 'INFO - Parsing args'; then
-                          #   echo "Test passed: cli.py returned log for argparse"
-                          # else
-                          #   echo "Test failed: cli.py did not return log for argparse"
-                          #   exit 1
-                          # fi
+                          # Check the logger showed the startup commands
+                          if cat ./agent/output.log | grep -q 'INFO - Parsing args'; then
+                            echo "Test passed: cli.py returned log for argparse"
+                          else
+                            echo "Test failed: cli.py did not return log for argparse"
+                            exit 1
+                          fi
 
-                          # # Check the chat completion returned
-                          # if cat ./agent/output.log | grep -q 'INFO - Starting DRUM runner'; then
-                          #   echo "Test passed: cli.py returned log for starting DRUM runner"
-                          # else
-                          #   echo "Test failed: cli.py did not return log for starting DRUM runner"
-                          #   exit 1
-                          # fi
+                          # Check the chat completion returned
+                          if cat ./agent/output.log | grep -q 'INFO - Starting DRUM runner'; then
+                            echo "Test passed: cli.py returned log for starting DRUM runner"
+                          else
+                            echo "Test failed: cli.py did not return log for starting DRUM runner"
+                            exit 1
+                          fi
 
-                          # # Check the chat completion returned
-                          # if cat ./agent/output.log | grep -q 'Running agent with user'; then
-                          #   echo "Test passed: cli.py returned log containing in-agent messaging"
-                          # else
-                          #   echo "Test failed: cli.py did not return log containing in-agent messaging"
-                          #   exit 1
-                          # fi
+                          # Check the chat completion returned
+                          if cat ./agent/output.log | grep -q 'Running agent with user'; then
+                            echo "Test passed: cli.py returned log containing in-agent messaging"
+                          else
+                            echo "Test failed: cli.py did not return log containing in-agent messaging"
+                            exit 1
+                          fi
 
-                          # # Check the chat completion returned
-                          # if cat ./agent/output.log | grep -q 'Stored execution result'; then
-                          #   echo "Test passed: cli.py returned log containing stored execution result"
-                          # else
-                          #   echo "Test failed: cli.py did not return log containing stored execution result"
-                          #   exit 1
-                          # fi
+                          # Check the chat completion returned
+                          if cat ./agent/output.log | grep -q 'Stored execution result'; then
+                            echo "Test passed: cli.py returned log containing stored execution result"
+                          else
+                            echo "Test failed: cli.py did not return log containing stored execution result"
+                            exit 1
+                          fi
 
-                          # # Check the chat completion returned
-                          # if cat ./agent/output.log | grep -q '"content": "success"'; then
-                          #   echo "Test passed: cli.py returned chat completion success"
-                          # else
-                          #   echo "Test failed: cli.py did not return chat completion success"
-                          #   exit 1
-                          # fi
+                          # Check the chat completion returned
+                          if cat ./agent/output.log | grep -q '"content": "success"'; then
+                            echo "Test passed: cli.py returned chat completion success"
+                          else
+                            echo "Test failed: cli.py did not return chat completion success"
+                            exit 1
+                          fi
                         envVariables:
                           UV_CACHE_DIR: /.uv_cache
                   - step:
@@ -146,11 +146,13 @@ pipeline:
                           echo "DATAROBOT_ENDPOINT=https://test.com/api/v2" >> .env
 
                           # Run the CLI command with a sample user prompt
+                          echo "Initial execution"
                           uvx --from go-task-bin task agent:cli -- \
                             execute \
                             --show_output \
                             --completion_json "example-completion.json" \
                             > ./agent/output.log 2>&1
+                          cat ./agent/output.log
 
                           # Check if the log file was created
                           if [ $(wc -l <./agent/output.log) -ge 13 ]; then
