Add cli test for streaming

diff --git a/.harness/pipelines/test-af-component-agent.yaml b/.harness/pipelines/test-af-component-agent.yaml
--- a/.harness/pipelines/test-af-component-agent.yaml
+++ b/.harness/pipelines/test-af-component-agent.yaml
@@ -174,6 +174,49 @@ pipeline:
                           fi
                         envVariables:
                           UV_CACHE_DIR: /.uv_cache
+                  - step:
+                      type: Run
+                      name: Base CLI Tests with streaming
+                      identifier: Base_CLI_Tests_with_Streaming
+                      spec:
+                        connectorRef: GHCR_HHI
+                        image: ghcr.io/astral-sh/uv:<+matrix.python>-bookworm
+                        shell: Sh
+                        command: |-
+                          cd ./copier_context
+                          echo "DATAROBOT_API_TOKEN=secret" > .env
+                          echo "DATAROBOT_ENDPOINT=https://test.com/api/v2" >> .env
+
+                          # Run the CLI command with a sample user prompt
+                          echo "Initial execution"
+                          uvx --from go-task-bin task agent:cli -- \
+                            execute \
+                            --show_output \
+                            --user_prompt '{"topic": "Artificial Intelligence"}' \
+                            --stream \
+                            > ./agent/output.log 2>&1
+                          cat ./agent/output.log
+
+                          # Check if the log file was created
+                          if [ $(wc -l <./agent/output.log) -ge 13 ]; then
+                            echo "Log file created successfully and file not empty."
+                            echo ""
+                            echo "Contents of output.log:"
+                            cat ./agent/output.log
+                          else
+                            echo "Log file was not created."
+                            exit 1
+                          fi
+
+                          # Check the chat completion returned
+                          if cat ./agent/output.log | grep -q '"content": "success"'; then
+                            echo "Test passed: cli.py returned chat completion success"
+                          else
+                            echo "Test failed: cli.py did not return chat completion success"
+                            exit 1
+                          fi
+                        envVariables:
+                          UV_CACHE_DIR: /.uv_cache
               platform:
                 os: Linux
                 arch: Amd64
