Update pipeline Test af-component-agent

diff --git a/.harness/pipelines/test-af-component-agent.yaml b/.harness/pipelines/test-af-component-agent.yaml
--- a/.harness/pipelines/test-af-component-agent.yaml
+++ b/.harness/pipelines/test-af-component-agent.yaml
@@ -45,6 +45,206 @@ pipeline:
                       uvx --from go-task-bin task agent_test:agent:test-coverage
                     envVariables:
                       UV_CACHE_DIR: /.uv_cache
+              - step:
+                  type: Run
+                  name: Base CLI Tests with DRUM using server mode
+                  identifier: Base_CLI_Tests_with_DRUM_using_server_mode
+                  spec:
+                    shell: Sh
+                    connectorRef: GHCR_HHI
+                    image: ghcr.io/astral-sh/uv:python3.11-bookworm-slim
+                    command: |-
+                      cd ./copier_context
+
+                      # Ensure the log file does not exist before running the CLI command
+                      if ! [ -f "output.log" ]; then
+                        echo "Log file not created yet. Proceeding with CLI test."
+                      else
+                        echo "Log file exists before test. CLI test cannot be run."
+                        exit 1
+                      fi
+
+                      # Run the CLI command with a sample user prompt
+                      task agent_test:agent:cli -- \
+                        execute \
+                        --user_prompt '{"topic": "Artificial Intelligence"}' \
+                        --disable_serverless \
+                        > ./agent/output.log 2>&1
+
+                      # Check if the log file was created
+                      if [ $(wc -l <./agent/output.log) -ge 13 ]; then
+                        echo "Log file created successfully and file not empty."
+                        echo ""
+                        echo "Contents of output.log:"
+                        cat ./agent/output.log
+                      else
+                        echo "Log file was not created."
+                        exit 1
+                      fi
+
+                      # Check the logger showed the first command
+                      if cat ./agent/output.log | grep -q 'Running CLI execute'; then
+                        echo "Test passed: cli.py returned log for starting cli"
+                      else
+                        echo "Test failed: cli.py did not return log for starting cli"
+                        exit 1
+                      fi
+
+                      # Check the logger showed the startup commands
+                      if cat ./agent/output.log | grep -q 'INFO - Parsing args'; then
+                        echo "Test passed: cli.py returned log for argparse"
+                      else
+                        echo "Test failed: cli.py did not return log for argparse"
+                        exit 1
+                      fi
+
+                      # Check the chat completion returned
+                      if cat ./agent/output.log | grep -q 'INFO - Starting DRUM server'; then
+                        echo "Test passed: cli.py returned log for starting DRUM server"
+                      else
+                        echo "Test failed: cli.py did not return log for starting DRUM server"
+                        exit 1
+                      fi
+
+                      # Check the chat completion returned
+                      if cat ./agent/output.log | grep -q 'INFO - Running agent with inputs'; then
+                        echo "Test passed: cli.py returned log containing in-agent messaging"
+                      else
+                        echo "Test failed: cli.py did not return log containing in-agent messaging"
+                        exit 1
+                      fi
+
+                      # Check the chat completion returned
+                      if cat ./agent/output.log | grep -q '"content": "success"'; then
+                        echo "Test passed: cli.py returned chat completion success"
+                      else
+                        echo "Test failed: cli.py did not return chat completion success"
+                        exit 1
+                      fi
+                    envVariables:
+                      UV_CACHE_DIR: /.uv_cache
+              - step:
+                  type: Run
+                  name: Base CLI Tests with DRUM using serverless mode
+                  identifier: Base_CLI_Tests_with_DRUM_using_serverless_mode
+                  spec:
+                    shell: Sh
+                    connectorRef: GHCR_HHI
+                    image: ghcr.io/astral-sh/uv:python3.11-bookworm-slim
+                    command: |-
+                      cd ./copier_context
+
+                      # Ensure the log file does not exist before running the CLI command
+                      if ! [ -f "output.log" ]; then
+                        echo "Log file not created yet. Proceeding with CLI test."
+                      else
+                        echo "Log file exists before test. CLI test cannot be run."
+                        exit 1
+                      fi
+
+                      # Run the CLI command with a sample user prompt
+                      task agent_test:agent:cli -- \
+                        execute \
+                        --user_prompt '{"topic": "Artificial Intelligence"}' \
+                        > ./agent/output.log 2>&1
+
+                      # Check if the log file was created
+                      if [ $(wc -l <./agent/output.log) -ge 13 ]; then
+                        echo "Log file created successfully and file not empty."
+                        echo ""
+                        echo "Contents of output.log:"
+                        cat ./agent/output.log
+                      else
+                        echo "Log file was not created."
+                        exit 1
+                      fi
+
+                      # Check the logger showed the first command
+                      if cat ./agent/output.log | grep -q 'Running CLI execute'; then
+                        echo "Test passed: cli.py returned log for starting cli"
+                      else
+                        echo "Test failed: cli.py did not return log for starting cli"
+                        exit 1
+                      fi
+
+                      # Check the logger showed the startup commands
+                      if cat ./agent/output.log | grep -q 'INFO - Parsing args'; then
+                        echo "Test passed: cli.py returned log for argparse"
+                      else
+                        echo "Test failed: cli.py did not return log for argparse"
+                        exit 1
+                      fi
+
+                      # Check the chat completion returned
+                      if cat ./agent/output.log | grep -q 'INFO - Starting DRUM runner'; then
+                        echo "Test passed: cli.py returned log for starting DRUM runner"
+                      else
+                        echo "Test failed: cli.py did not return log for starting DRUM runner"
+                        exit 1
+                      fi
+
+                      # Check the chat completion returned
+                      if cat ./agent/output.log | grep -q 'Running agent with inputs'; then
+                        echo "Test passed: cli.py returned log containing in-agent messaging"
+                      else
+                        echo "Test failed: cli.py did not return log containing in-agent messaging"
+                        exit 1
+                      fi
+
+                      # Check the chat completion returned
+                      if cat ./agent/output.log | grep -q '"content": "success"'; then
+                        echo "Test passed: cli.py returned chat completion success"
+                      else
+                        echo "Test failed: cli.py did not return chat completion success"
+                        exit 1
+                      fi
+                    envVariables:
+                      UV_CACHE_DIR: /.uv_cache
+              - step:
+                  type: Run
+                  name: Base CLI Tests with JSON
+                  identifier: Base_CLI_Tests_with_JSON
+                  spec:
+                    shell: Sh
+                    connectorRef: GHCR_HHI
+                    image: ghcr.io/astral-sh/uv:python3.11-bookworm-slim
+                    command: |-
+                      cd ./copier_context
+
+                      # Ensure the log file does not exist before running the CLI command
+                      if ! [ -f "output.log" ]; then
+                        echo "Log file not created yet. Proceeding with CLI test."
+                      else
+                        echo "Log file exists before test. CLI test cannot be run."
+                        exit 1
+                      fi
+
+                      # Run the CLI command with a sample user prompt
+                      task agent_test:agent:cli -- \
+                        execute \
+                        --completion_json "example-completion.json" \
+                        > ./agent/output.log 2>&1
+
+                      # Check if the log file was created
+                      if [ $(wc -l <./agent/output.log) -ge 13 ]; then
+                        echo "Log file created successfully and file not empty."
+                        echo ""
+                        echo "Contents of output.log:"
+                        cat ./agent/output.log
+                      else
+                        echo "Log file was not created."
+                        exit 1
+                      fi
+
+                      # Check the chat completion returned
+                      if cat ./agent/output.log | grep -q '"content": "success"'; then
+                        echo "Test passed: cli.py returned chat completion success"
+                      else
+                        echo "Test failed: cli.py did not return chat completion success"
+                        exit 1
+                      fi
+                    envVariables:
+                      UV_CACHE_DIR: /.uv_cache
           platform:
             os: Linux
             arch: Amd64
