Add CLI tests

diff --git a/.github/workflows/afcomponentagent-cli-test.yaml b/.github/workflows/afcomponentagent-cli-test.yaml
--- a/.github/workflows/afcomponentagent-cli-test.yaml
+++ b/.github/workflows/afcomponentagent-cli-test.yaml
@@ -116,3 +116,76 @@ jobs:
           fi
         env:
           UV_CACHE_DIR: /.uv_cache
+      - name: Run CLI Tests with JSON input
+        shell: sh
+        run: |
+          cd ./rendered
+          echo "DATAROBOT_API_TOKEN=secret" > .env
+          echo "DATAROBOT_ENDPOINT=https://test.com/api/v2" >> .env
+
+          # Run the CLI command with a sample user prompt
+          echo "Initial execution"
+          uvx --from go-task-bin task agent:cli -- \
+            execute \
+            --show_output \
+            --completion_json "example-completion.json" \
+            > ./agent/output.log 2>&1
+          cat ./agent/output.log
+
+          # Check if the log file was created
+          if [ $(wc -l <./agent/output.log) -ge 13 ]; then
+            echo "Log file created successfully and file not empty."
+            echo ""
+            echo "Contents of output.log:"
+            cat ./agent/output.log
+          else
+            echo "Log file was not created."
+            exit 1
+          fi
+
+          # Check the chat completion returned
+          if cat ./agent/output.log | grep -q '"content": "success"'; then
+            echo "Test passed: cli.py returned chat completion success"
+          else
+            echo "Test failed: cli.py did not return chat completion success"
+            exit 1
+          fi
+        env:
+          UV_CACHE_DIR: /.uv_cache
+      - name: Run CLI Tests with streaming enabled
+        shell: sh
+        run: |
+          cd ./rendered
+          echo "DATAROBOT_API_TOKEN=secret" > .env
+          echo "DATAROBOT_ENDPOINT=https://test.com/api/v2" >> .env
+
+          # Run the CLI command with a sample user prompt
+          echo "Initial execution"
+          uvx --from go-task-bin task agent:cli -- \
+            execute \
+            --show_output \
+            --user_prompt '{"topic": "Artificial Intelligence"}' \
+            --stream \
+            > ./agent/output.log 2>&1
+          cat ./agent/output.log
+
+          # Check if the log file was created
+          if [ $(wc -l <./agent/output.log) -ge 13 ]; then
+            echo "Log file created successfully and file not empty."
+            echo ""
+            echo "Contents of output.log:"
+            cat ./agent/output.log
+          else
+            echo "Log file was not created."
+            exit 1
+          fi
+
+          # Check the streaming returned
+          if cat ./agent/output.log | grep -q '"content": "streaming success"'; then
+            echo "Test passed: cli.py returned streaming success"
+          else
+            echo "Test failed: cli.py did not return streaming success"
+            exit 1
+          fi
+        env:
+          UV_CACHE_DIR: /.uv_cache
