[BUZZOK-26141] Add ability to send chat completion json file (#83)
* Add ability to send chat completion json file

* Add logs

* Update docs

* Fix tests

* Rename

* Update testing

diff --git a/.github/workflows/component-base-test.yml b/.github/workflows/component-base-test.yml
--- a/.github/workflows/component-base-test.yml
+++ b/.github/workflows/component-base-test.yml
@@ -190,3 +190,58 @@ jobs:
             echo "Test failed: cli.py did not return chat completion success"
             exit 1
           fi
+  uvx-copier-cli-json-test:
+    name: Base CLI JSON Tests
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+      - name: Install uv
+        uses: astral-sh/setup-uv@v5
+      - name: Install Task
+        uses: arduino/setup-task@v2
+      - name: Install Dependencies
+        run: |
+          uvx copier copy . ./copier_context --defaults
+          cp ./fixtures/Taskfile.yml ./copier_context/Taskfile.yml
+          cp ./fixtures/infra/pyproject.toml ./copier_context/infra/pyproject.toml
+          cp ./fixtures/infra/__init__.py ./copier_context/infra/infra/__init__.py
+          
+          cd ./copier_context
+          task agent_test:agent:req
+      - name: Run cli test
+        run: |-
+          cd ./copier_context
+
+          # Ensure the log file does not exist before running the CLI command
+          if ! [ -f "output.log" ]; then
+            echo "Log file not created yet. Proceeding with CLI test."
+          else
+            echo "Log file exists before test. CLI test cannot be run."
+            exit 1
+          fi
+
+          # Run the CLI command with a sample user prompt
+          task agent_test:agent:cli -- \
+            execute \
+            --completion_json "example-completion.json" \
+            > ./agent/output.log 2>&1
+
+          # Check if the log file was created
+          if [ $(wc -l <./agent/output.log) -ge 13 ]; then
+            echo "Log file created successfully and file not empty."
+            echo ""
+            echo "Contents of output.log:"
+            cat ./agent/output.log
+          else
+            echo "Log file was not created."
+            exit 1
+          fi
+          
+          # Check the chat completion returned
+          if cat ./agent/output.log | grep -q '"content": "success"'; then
+            echo "Test passed: cli.py returned chat completion success"
+          else
+            echo "Test failed: cli.py did not return chat completion success"
+            exit 1
+          fi
