Update testing and flushes

diff --git a/.github/workflows/component-base-test.yml b/.github/workflows/component-base-test.yml
--- a/.github/workflows/component-base-test.yml
+++ b/.github/workflows/component-base-test.yml
@@ -139,13 +139,6 @@ jobs:
             execute \
             --user_prompt '{"topic": "Artificial Intelligence"}' \
             > ./agent/output.log 2>&1
-          
-          if cat ./agent/output.log | grep -q '"content": "success"'; then
-            echo "Test passed: cli.py returned success"
-          else
-            echo "Test failed: cli.py did not return success"
-            exit 1
-          fi
 
           # Check if the log file was created
           if [ $(wc -l <./agent/output.log) -ge 13 ]; then
@@ -155,5 +148,45 @@ jobs:
             cat ./agent/output.log
           else
             echo "Log file was not created."
+            exit 1
+          fi
+          
+          # Check the logger showed the first command
+          if cat ./agent/output.log | grep -q 'Running CLI execute'; then
+            echo "Test passed: cli.py returned log for starting cli"
+          else
+            echo "Test failed: cli.py did not return log for starting cli"
+            exit 1
+          fi
+          
+          # Check the logger showed the startup commands
+          if cat ./agent/output.log | grep -q 'INFO - Parsing args'; then
+            echo "Test passed: cli.py returned log for argparse"
+          else
+            echo "Test failed: cli.py did not return log for argparse"
+            exit 1
+          fi
+          
+          # Check the chat completion returned
+          if cat ./agent/output.log | grep -q 'INFO - Starting DRUM server'; then
+            echo "Test passed: cli.py returned log for starting DRUM server"
+          else
+            echo "Test failed: cli.py did not return log for starting DRUM server"
+            exit 1
+          fi
+          
+          # Check the chat completion returned
+          if cat ./agent/output.log | grep -q 'INFO - Running agent with inputs'; then
+            echo "Test passed: cli.py returned log containing in-agent messaging"
+          else
+            echo "Test failed: cli.py did not return log containing in-agent messaging"
+            exit 1
+          fi
+          
+          # Check the chat completion returned
+          if cat ./agent/output.log | grep -q '"content": "success"'; then
+            echo "Test passed: cli.py returned chat completion success"
+          else
+            echo "Test failed: cli.py did not return chat completion success"
             exit 1
           fi
