Add cli testing

diff --git a/.github/workflows/component-base-test.yml b/.github/workflows/component-base-test.yml
--- a/.github/workflows/component-base-test.yml
+++ b/.github/workflows/component-base-test.yml
@@ -60,8 +60,36 @@ jobs:
       - name: Create Copier Template
         run: |
           uvx copier copy . ./copier_context --defaults
-      - name: Lint Template
+      - name: Run unit tests
         run: |
           cd ./copier_context/agent
           task req
           task test
+
+  uvx-copier-unit-test:
+    name: "Base Unit Tests"
+    runs-on: "ubuntu-latest"
+    defaults:
+      run:
+        working-directory: .
+    steps:
+      - name: Checkout
+        uses: "actions/checkout@v4"
+      - name: Install uv
+        uses: astral-sh/setup-uv@v5
+      - name: Install Task
+        uses: arduino/setup-task@v2
+      - name: Create Copier Template
+        run: |
+          uvx copier copy . ./copier_context --defaults
+      - name: Run cli test
+        run: |
+          cd ./copier_context/agent
+          task req
+          task cli -- execute --user_prompt '{"topic": "Artificial Intelligence"}'
+          if task cli -- execute --user_prompt '{"topic": "Artificial Intelligence"}' | grep -q '"content": "success"'; then
+            echo "Test passed: cli.py returned success"
+          else
+            echo "Test failed: cli.py did not return success"
+            exit 1
+          fi
